# Generated by Django 5.1.4 on 2024-12-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FCART_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
