# Generated by Django 5.1.4 on 2024-12-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FCART_APP', '0002_alter_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
